FROM node:18-alpine

WORKDIR /usr/src/app

ARG NEXT_PUBLIC_SERVER_URL=
ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

COPY client/package.json .
COPY yarn.lock .

RUN yarn

COPY ./client .

RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]
