version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "4000:4000"
    links:
      - "redis"
      - "db"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/build/
      - server_ssh_key:/root/.ssh
    depends_on:
      - db
      - redis
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:@db:5432/ledokku?schema=public&connect_timeout=300
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=
      - GITHUB_APP_ID=
      - GITHUB_APP_NAME=
      - GITHUB_APP_CLIENT_ID=
      - GITHUB_APP_CLIENT_SECRET=
      - GITHUB_APP_WEBHOOK_SECRET=
      - GITHUB_APP_PEM=
      - DOKKU_SSH_HOST=dokku
      - DOKKU_SSH_PORT=22
      - NUMBER_USERS_ALLOWED=1
      - TELEMETRY_DISABLED=1

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 

  redis:
    restart: always
    image: 'redis:6'

volumes:
  db_data:
  server_ssh_key:

networks:
  default:
    name: proxy
    external: true
