FROM dokku/dokku:latest

WORKDIR /usr/src/app


RUN sudo apt update

RUN curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
RUN sudo apt -y install nodejs

RUN npm install --global yarn

COPY server/package.json .
COPY yarn.lock .

RUN yarn

COPY ./server .

RUN yarn prisma:generate
RUN yarn build

EXPOSE 4000
CMD [ "yarn", "start" ]
